# Generated by Django 5.1.3 on 2024-11-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataConverter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateCVSStructure',
            new_name='CreateCBSStructure',
        ),
    ]
