# Generated by Django 5.1.3 on 2024-11-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConverter', '0002_rename_createcvsstructure_createcbsstructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEstimate',
            fields=[
                ('abstracfileuploader_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataConverter.abstracfileuploader')),
            ],
            bases=('dataConverter.abstracfileuploader',),
        ),
    ]
